### ISSUE TITLE
the process event adress 

### ISSUE THREAD

**Issue by sopoka1999** [CarsonARK/noJailbreak-Hook-UE4#1]
how to get the process event adress？

*(long*)( *MyShooterWeapon + 0x230) = (long)WeaponProcessEvent;

**Comment by CarsonARK** [comment]
To get the game original process event address, you change the address, you can Read<long>(*MyShooterWeapon + 0x230) - (long)_dyld_get_image_header(0)

**Comment by sopoka1999** [comment]
How do you know that *MyShooterWeapon + **0x230** is bound to this function. I only know to get the attributes of each class through the sdk? Thanks

**Comment by CarsonARK** [comment]
because when you read the code in IDA or Ghidra, read any Server function for the game you are working on. For ARK, the process event address is stored at 0x230, while in other games it may be different. The server function finds the function pointer for process event by looking at that address, so in order to find it you can do the same.
